table 무더위쉼터
	lineageTag: a0012ddb-5b13-4a18-87cb-32ea54b24adb

	column 쉼터번호
		dataType: int64
		formatString: 0
		lineageTag: 04df0f07-3336-4bc9-a701-69d3fa162b5e
		summarizeBy: sum
		sourceColumn: 쉼터번호

		annotation SummarizationSetBy = Automatic

	column 쉼터명
		dataType: string
		lineageTag: 0825c316-fad2-4237-aadd-7760238b7eaf
		summarizeBy: none
		sourceColumn: 쉼터명

		annotation SummarizationSetBy = Automatic

	column 도로명주소
		dataType: string
		lineageTag: aeef5b9d-8593-4497-a1fb-1873a90462bb
		summarizeBy: none
		sourceColumn: 도로명주소

		annotation SummarizationSetBy = Automatic

	column 시도
		dataType: string
		lineageTag: e05a6eaa-7bfe-4b6b-be3f-a423124373cd
		summarizeBy: none
		sourceColumn: 시도

		annotation SummarizationSetBy = Automatic

	column 시도코드
		dataType: string
		lineageTag: c12d6c1f-5814-4c84-aea4-40c3b289a673
		summarizeBy: none
		sourceColumn: 시도코드

		annotation SummarizationSetBy = Automatic

	column 시군구
		dataType: string
		lineageTag: eede1755-1802-4853-b594-fab41c2180ea
		summarizeBy: none
		sourceColumn: 시군구

		annotation SummarizationSetBy = Automatic

	column 시군구코드
		dataType: string
		lineageTag: 7461264e-609a-4128-9c74-bdf1dad57d4b
		summarizeBy: none
		sourceColumn: 시군구코드

		annotation SummarizationSetBy = Automatic

	column 읍면동
		dataType: string
		lineageTag: 1efd0872-c280-4d7d-8612-3ee0c747f96a
		summarizeBy: none
		sourceColumn: 읍면동

		annotation SummarizationSetBy = Automatic

	column 위치정밀도
		dataType: string
		lineageTag: 9cc98ea0-0dd0-4bce-a49b-490f4d667cf5
		summarizeBy: none
		sourceColumn: 위치정밀도

		annotation SummarizationSetBy = Automatic

	column 권역명
		dataType: string
		lineageTag: 70a1dd75-a1ed-44ac-aa0b-2523f88c60d6
		summarizeBy: none
		sourceColumn: 권역명

		annotation SummarizationSetBy = Automatic

	column 지역코드
		dataType: int64
		formatString: 0
		lineageTag: 3c3ef377-a594-46ec-8690-af2c8724aaae
		summarizeBy: sum
		sourceColumn: 지역코드

		annotation SummarizationSetBy = Automatic

	column 위도
		dataType: double
		lineageTag: 5911c87b-eb01-477f-954e-1148940548e4
		summarizeBy: sum
		sourceColumn: 위도

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 경도
		dataType: double
		lineageTag: 23879e4e-0af3-418d-93e7-a50c876e18f7
		summarizeBy: sum
		sourceColumn: 경도

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 이용가능인원
		dataType: int64
		formatString: 0
		lineageTag: a591eb86-1a6e-488d-8dae-294864c24ab7
		summarizeBy: sum
		sourceColumn: 이용가능인원

		annotation SummarizationSetBy = Automatic

	column 면적
		dataType: double
		lineageTag: f13d8a8b-5ac4-4ec1-95bb-0c9a1ef0695c
		summarizeBy: sum
		sourceColumn: 면적

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 에어컨수
		dataType: int64
		formatString: 0
		lineageTag: b6bc53ea-1a33-455a-b0d0-c5e147e301b5
		summarizeBy: sum
		sourceColumn: 에어컨수

		annotation SummarizationSetBy = Automatic

	column 선풍기수
		dataType: int64
		formatString: 0
		lineageTag: ae1b993b-acf0-4e68-9908-be4bd6d3c7c9
		summarizeBy: sum
		sourceColumn: 선풍기수

		annotation SummarizationSetBy = Automatic

	column 에어컨보유여부
		dataType: string
		lineageTag: bb78a1ae-2ba2-42b0-9798-eb597e886b65
		summarizeBy: none
		sourceColumn: 에어컨보유여부

		annotation SummarizationSetBy = Automatic

	column 냉방설비여부
		dataType: string
		lineageTag: 6e8171f4-df4c-43d6-abb2-de29f9235e69
		summarizeBy: none
		sourceColumn: 냉방설비여부

		annotation SummarizationSetBy = Automatic

	column 야간개방여부
		dataType: string
		lineageTag: e1c40645-8d26-4e2c-8f92-04686b01434e
		summarizeBy: none
		sourceColumn: 야간개방여부

		annotation SummarizationSetBy = Automatic

	column 주말휴일개방여부
		dataType: string
		lineageTag: 63a8e063-5a99-4f62-ad0e-07248b8a7266
		summarizeBy: none
		sourceColumn: 주말휴일개방여부

		annotation SummarizationSetBy = Automatic

	column 숙박가능여부
		dataType: string
		lineageTag: 1ecce010-07dc-4c36-a995-adca0eab3897
		summarizeBy: none
		sourceColumn: 숙박가능여부

		annotation SummarizationSetBy = Automatic

	partition 무더위쉼터 = m
		mode: import
		source =
				let
				    원본 = Excel.Workbook(File.Contents("C:\Users\young\Downloads\무더위쉼터_최종.xlsx"), null, true),
				    무더위쉼터_Sheet = 원본{[Item="무더위쉼터",Kind="Sheet"]}[Data],
				    #"승격된 헤더" = Table.PromoteHeaders(무더위쉼터_Sheet, [PromoteAllScalars=true]),
				    #"변경된 유형" = Table.TransformColumnTypes(#"승격된 헤더",{{"쉼터번호", Int64.Type}, {"쉼터명", type text}, {"도로명주소", type text}, {"시도", type text}, {"시도코드", type text}, {"시군구", type text}, {"시군구코드", type text}, {"읍면동", type text}, {"위치정밀도", type text}, {"권역명", type text}, {"지역코드", Int64.Type}, {"위도", type number}, {"경도", type number}, {"이용가능인원", Int64.Type}, {"면적", type number}, {"에어컨수", Int64.Type}, {"선풍기수", Int64.Type}, {"에어컨보유여부", type text}, {"냉방설비여부", type text}, {"야간개방여부", type text}, {"주말휴일개방여부", type text}, {"숙박가능여부", type text}}),
				    #"제거된 빈 행" = Table.SelectRows(#"변경된 유형", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"제거된 빈 행"

	annotation PBI_NavigationStepName = 탐색

	annotation PBI_ResultType = Table

