table 시군구
	lineageTag: 0efcd3be-cccb-4b94-a3b4-e20c32c5b589

	measure 수용인원_중앙값 =
			
			MEDIANX(
			    VALUES('시군구'[시군구코드]),
			    [고령인구 1천명당 수용인원]
			)
		lineageTag: 3c0117ad-5e8d-46fd-832f-9a0671d3a7e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 시군구코드
		dataType: string
		lineageTag: 51db8446-7a04-4ba7-9095-51ebf1bcbeec
		summarizeBy: none
		sourceColumn: 시군구코드

		annotation SummarizationSetBy = Automatic

	column 시군구
		dataType: string
		lineageTag: 132a4055-f61b-40c0-bcd7-864d24cb9952
		summarizeBy: none
		sourceColumn: 시군구

		annotation SummarizationSetBy = Automatic

	column 시도코드
		dataType: string
		lineageTag: 3122e24a-56d3-4f1d-a8ab-4ffc1105cced
		summarizeBy: none
		sourceColumn: 시도코드

		annotation SummarizationSetBy = Automatic

	column 분석_고령인구 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COALESCE(
			    LOOKUPVALUE(
			        '인구(6월 기준)'[고령인구(65세 이상)],
			        '인구(6월 기준)'[시군구코드],
			        CurrentCode
			    ),
			    0
			)
		formatString: #,0
		lineageTag: 37900f21-d1fd-41f5-8121-1adfd347ac0b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_전체인구 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COALESCE(
			    LOOKUPVALUE(
			        '인구(6월 기준)'[전체인구],
			        '인구(6월 기준)'[시군구코드],
			        CurrentCode
			    ),
			    0
			)
		formatString: 0
		lineageTag: 8d39816e-764e-4b93-b25a-328ea07f3f90
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_온열질환자수 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COALESCE(
			    LOOKUPVALUE(
			        '전체기간_온열질환'[온열질환자수],
			        '전체기간_온열질환'[시군구코드],
			        CurrentCode
			    ),
			    0
			)
		formatString: 0
		lineageTag: 056b4735-7619-4186-8c0c-081a9878f81c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_추정사망자수 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COALESCE(
			    LOOKUPVALUE(
			        '전체기간_온열질환'[추정사망자수],
			        '전체기간_온열질환'[시군구코드],
			        CurrentCode
			    ),
			    0
			)
		formatString: 0
		lineageTag: 110326c5-86ea-45cf-9cb2-83deb1afe449
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_폭염일수 =
			
			LOOKUPVALUE(
			    '시군구_폭염일수'[폭염일수],
			    '시군구_폭염일수'[시군구코드],
			    '시군구'[시군구코드]
			)
		formatString: 0
		lineageTag: 76c24b74-c2c7-47c8-9674-54830acdb0fa
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_폭염단위구분 =
			
			COALESCE(
			    LOOKUPVALUE(
			        '시군구_폭염일수'[폭염_단위구분],
			        '시군구_폭염일수'[시군구코드],
			        '시군구'[시군구코드]
			    ),
			    "매칭없음"
			)
		lineageTag: 72de876a-d761-41a4-a887-862f813b31f1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 분석_쉼터수 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COUNTROWS(
			    FILTER(
			        '무더위쉼터',
			        '무더위쉼터'[시군구코드] = CurrentCode
			    )
			)
		formatString: 0
		lineageTag: e9e5b2aa-ad25-4586-be78-501f123f3dab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 분석_쉼터수용인원 =
			
			VAR CurrentCode = '시군구'[시군구코드]
			RETURN
			COALESCE(
			    SUMX(
			        FILTER(
			            '무더위쉼터',
			            '무더위쉼터'[시군구코드] = CurrentCode
			        ),
			        '무더위쉼터'[이용가능인원]
			    ),
			    0
			)
		formatString: #,0
		lineageTag: 3a0af4bc-0c72-4103-a443-21292d911d18
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '고령인구 비율_열' =
			
			DIVIDE(
			    '시군구'[분석_고령인구],
			    '시군구'[분석_전체인구],
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b0455855-1364-4c0c-9b6d-6dcca6640184
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '온열질환 발생률_열' =
			
			DIVIDE(
			    '시군구'[분석_온열질환자수],
			    '시군구'[분석_전체인구],
			    0
			) * 100000
		formatString: 0.0
		lineageTag: 0462d5dc-ee01-45b4-8f19-0ea81712db0b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '고령인구 1만명당 쉼터수_열' =
			
			DIVIDE(
			    '시군구'[분석_쉼터수],
			    '시군구'[분석_고령인구],
			    0
			) * 10000
		formatString: 0.0
		lineageTag: 6fecdb0c-1127-4494-891a-d157b697a8af
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '고령인구 1천명당 수용인원_열' =
			
			DIVIDE(
			    '시군구'[분석_쉼터수용인원],
			    '시군구'[분석_고령인구],
			    0
			) * 1000
		formatString: 0.0
		lineageTag: fce7a43e-c189-4bc8-ba28-f46b660e6580
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 노출높음_Flag =
			
			VAR NationalMedian =
			    MEDIANX(
			        ALL('시군구'[분석_폭염일수]),
			        '시군구'[분석_폭염일수]
			    )
			RETURN
			IF(
			    '시군구'[분석_폭염일수] >= NationalMedian,
			    1,
			    0
			)
		formatString: 0
		lineageTag: b630d769-fd1c-48ff-9946-a7a163ed0a19
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 민감도높음_Flag =
			
			VAR NationalMedian =
			    MEDIANX(
			        ALL('시군구'[고령인구 비율_열]),
			        '시군구'[고령인구 비율_열]
			    )
			RETURN
			IF(
			    '시군구'[고령인구 비율_열] >= NationalMedian,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 0f6fe9f9-6bb3-4a32-95d9-e270bd718bfa
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 대응부족_Flag =
			
			VAR NationalMedian =
			    MEDIANX(
			        ALL('시군구'[고령인구 1천명당 수용인원_열]),
			        '시군구'[고령인구 1천명당 수용인원_열]
			    )
			RETURN
			IF(
			    '시군구'[고령인구 1천명당 수용인원_열] < NationalMedian,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 83c26a35-eaa9-490f-bbf1-0170616feff2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 피해높음_Flag =
			
			VAR NationalMedian =
			    MEDIANX(
			        ALL('시군구'[온열질환 발생률_열]),
			        '시군구'[온열질환 발생률_열]
			    )
			RETURN
			IF(
			    '시군구'[온열질환 발생률_열] >= NationalMedian,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 8bcd7a31-8bf2-4b25-8b62-8b7580d12021
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '구조적 위험요인 수' =
			
			'시군구'[노출높음_Flag]
			    + '시군구'[민감도높음_Flag]
			    + '시군구'[대응부족_Flag]
		formatString: 0
		lineageTag: b133dbbe-bc09-40a7-aff3-ac0378e76d5b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '사각지대 유형' =
			
			VAR RiskCount = '시군구'[구조적 위험요인 수]
			VAR HighDamage = '시군구'[피해높음_Flag]
			RETURN
			SWITCH(
			    TRUE(),
			
			    RiskCount = 3 && HighDamage = 1,
			        "현재 사각지대",
			
			    RiskCount = 3 && HighDamage = 0,
			        "잠재 사각지대",
			
			    RiskCount = 2 && HighDamage = 1,
			        "주의지역",
			
			    RiskCount <= 1 && HighDamage = 1,
			        "피해 집중지역",
			
			    '시군구'[노출높음_Flag] = 1
			        && '시군구'[민감도높음_Flag] = 1
			        && '시군구'[대응부족_Flag] = 0
			        && HighDamage = 0,
			        "대응 양호 후보",
			
			    "기타 지역"
			)
		lineageTag: abd1552b-cb03-4c7c-bd53-2acc414fb185
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 폭염일수_구간 =
			
			SWITCH(TRUE(),
			    [분석_폭염단위구분] = "관측자료없음_0처리", "데이터 없음",
			    [분석_폭염일수] <= 5, "1~5일",
			    [분석_폭염일수] <= 10, "6~10일",
			    [분석_폭염일수] <= 15, "11~15일",
			    [분석_폭염일수] <= 20, "16~20일",
			    "21일 이상"
			)
		lineageTag: ddb3634a-3112-4259-852c-78727a831499
		summarizeBy: none
		sortByColumn: '폭염일수 구간 정렬'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column '폭염일수 구간 정렬' =
			
			SWITCH(
			    TRUE(),
			    '시군구'[분석_폭염일수] = 0, 1,
			    '시군구'[분석_폭염일수] <= 5, 2,
			    '시군구'[분석_폭염일수] <= 10, 3,
			    '시군구'[분석_폭염일수] <= 15, 4,
			    '시군구'[분석_폭염일수] <= 20, 5,
			    6
			)
		formatString: 0
		lineageTag: 0f04ca57-fed9-40cd-9eda-a8084d517bfa
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 시군구_표시 =
			
			LOOKUPVALUE( '시도'[시도], '시도'[시도코드], '시군구'[시도코드] )
			    & " " & '시군구'[시군구]
		lineageTag: e35771bd-ac3d-465d-9e31-7d9d0176720c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 시군구 = m
		mode: import
		source =
				let
				    원본 = Excel.Workbook(File.Contents("C:\Users\young\Downloads\시군구코드.xlsx"), null, true),
				    시군구_Sheet = 원본{[Item="시군구",Kind="Sheet"]}[Data],
				    #"승격된 헤더" = Table.PromoteHeaders(시군구_Sheet, [PromoteAllScalars=true]),
				    #"변경된 유형" = Table.TransformColumnTypes(#"승격된 헤더",{{"시군구코드", type text}, {"시군구", type text}, {"시도코드", type text}}),
				    #"제거된 빈 행" = Table.SelectRows(#"변경된 유형", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"제거된 빈 행"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 탐색

